// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQfMteD22WC2uLj4gq_g0geqPdgrtbJHY',
    appId: '1:9182085141:web:60265681f8f7f446b38e1c',
    messagingSenderId: '9182085141',
    projectId: 'kelompok-todolist-f2cc5',
    authDomain: 'kelompok-todolist-f2cc5.firebaseapp.com',
    storageBucket: 'kelompok-todolist-f2cc5.firebasestorage.app',
    measurementId: 'G-XBPQFQMVGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1C13iQDBmpHsi4zY1wDNrCywWGYcDLUg',
    appId: '1:9182085141:android:f2c7edc8f97501aab38e1c',
    messagingSenderId: '9182085141',
    projectId: 'kelompok-todolist-f2cc5',
    storageBucket: 'kelompok-todolist-f2cc5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQfMteD22WC2uLj4gq_g0geqPdgrtbJHY',
    appId: '1:9182085141:web:bc698dcc29cf939db38e1c',
    messagingSenderId: '9182085141',
    projectId: 'kelompok-todolist-f2cc5',
    authDomain: 'kelompok-todolist-f2cc5.firebaseapp.com',
    storageBucket: 'kelompok-todolist-f2cc5.firebasestorage.app',
    measurementId: 'G-LBKPLF7GJD',
  );
}
